"""add created_at to agent_tasks

Revision ID: 38c45a78677c
Revises: d618229fef36
Create Date: 2025-06-08 12:01:51.082621

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38c45a78677c"
down_revision: Union[str, None] = "d618229fef36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_tasks", sa.Column("created_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agent_tasks", "created_at")
    # ### end Alembic commands ###
