name: Build, Test, and Deploy Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: "3.11"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with black and flake8
        run: |
          black --check .
          flake8 --max-line-length=88 --ignore=E501,E203,W503 --exclude=env .

      - name: Run tests with coverage
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          MONGODB_DATABASE: "easydo_test"
          ANTHROPIC_API_KEY: "test-key-for-pytest"
        run: |
          coverage run --source='.' -m pytest
          coverage report -m

      - name: Create ZIP file for deployment
        run: zip -r deploy.zip . -x ".git/*" "env/*" "*__pycache__/*" ".DS_Store" "tests/*" "*.pyc" "*.pyo" "*.pyd"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload package to S3 bucket
        run: aws s3 cp deploy.zip s3://${{ secrets.EB_S3_BUCKET_NAME }}/deploy-${{ github.sha }}.zip

      - name: Create new Elastic Beanstalk version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label "ver-${{ github.sha }}" \
            --source-bundle S3Bucket="${{ secrets.EB_S3_BUCKET_NAME }}",S3Key="deploy-${{ github.sha }}.zip"

      - name: Deploy new version and wait for completion
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label "ver-${{ github.sha }}"
          
          echo "Deployment initiated. Waiting for environment to become Ready..."
          aws elasticbeanstalk wait environment-updated --environment-name ${{ secrets.EB_ENV_NAME }}
          echo "Environment update complete."

      - name: Upload coverage report to Coveralls
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github